name: "elementary_tutorial"

config-version: 2
version: "1.0.0"

profile: "elementary_tutorial"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  ## see docs: https://docs.elementary-data.com/
  elementary:
  ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"
    ## To disable elementary for dev, uncomment this:
    # enabled: "{{ target.name in ['prod','analytics'] }}"

# Required from dbt 1.8 and above for certain Elementary features
flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True
